import { getSession } from '@/lib/auth'
import { PrismaClient } from '@prisma/client'
import { MarginaliaNote } from '@/components/ui/MarginaliaNote'
import { EmptyState } from '@/components/ui/EmptyState'
import { redirect } from 'next/navigation'
import { Sparkles, ArrowRight } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/Button'

const prisma = new PrismaClient()

export default async function RecommendationsPage() {
  const session = await getSession()

  if (!session || session.role !== 'STUDENT') {
    redirect('/login')
  }

  const recommendations = await prisma.aIInsight.findMany({
    where: { userId: session.id },
    orderBy: { generatedAt: 'desc' }
  })

  const atRisk = recommendations.filter(r => r.type === 'AT_RISK')
  const suggestions = recommendations.filter(r => r.type === 'RECOMMENDATION')
  const positive = recommendations.filter(r => r.type === 'POSITIVE')

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-ink">AI Recommendations</h1>
        <p className="text-ink/60 mt-2">
          Personalized insights and interventions generated by the 4D EduPortal AI Engine.
        </p>
      </div>

      {recommendations.length === 0 ? (
        <EmptyState 
          title="No recommendations yet" 
          description="The AI engine is currently analyzing your coursework. Check back soon for personalized insights."
          icon={<Sparkles className="w-8 h-8" />}
        />
      ) : (
        <div className="grid lg:grid-cols-3 gap-8">
          
          {/* Main Feed */}
          <div className="lg:col-span-2 space-y-6">
            <h2 className="text-xl font-bold text-ink mb-4">Latest Insights Feed</h2>
            
            <div className="space-y-4">
              {recommendations.map((insight) => {
                const tone = insight.type === 'AT_RISK' ? 'warning' : insight.type === 'POSITIVE' ? 'success' : 'insight'
                
                return (
                  <MarginaliaNote key={insight.id} tone={tone} className="p-6">
                    <div className="flex flex-col w-full">
                      <div className="flex justify-between items-center mb-3">
                        <span className="font-bold text-xs uppercase tracking-wider opacity-80">
                          {insight.type.replace('_', ' ')}
                        </span>
                        <span className="text-xs font-medium opacity-60">
                          {insight.generatedAt.toLocaleDateString()}
                        </span>
                      </div>
                      <p className="text-base text-ink/90 leading-relaxed mb-4">
                        {insight.content}
                      </p>
                      
                      {insight.type === 'AT_RISK' && (
                        <div className="mt-2 pt-4 border-t border-yellow-300/50">
                          <Link href="/dashboard/progress">
                            <Button variant="outline" size="sm" className="bg-white/50 border-yellow-400 text-yellow-900 hover:bg-yellow-100 w-full sm:w-auto">
                              Review Subject Metrics <ArrowRight className="w-4 h-4 ml-2" />
                            </Button>
                          </Link>
                        </div>
                      )}
                    </div>
                  </MarginaliaNote>
                )
              })}
            </div>
          </div>

          {/* AI Stats / Filters Panel */}
          <div className="lg:col-span-1 space-y-6">
            <div className="bg-parchment rounded-xl p-6 border border-ledger-line">
              <h3 className="font-bold text-ink mb-4 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary-red" />
                AI Engine Stats
              </h3>
              
              <ul className="space-y-4">
                <li className="flex justify-between items-center">
                  <span className="text-sm font-medium text-ink/70">Total Insights</span>
                  <span className="font-bold text-ink">{recommendations.length}</span>
                </li>
                <li className="flex justify-between items-center">
                  <span className="text-sm font-medium text-ink/70">Action Required</span>
                  <span className="font-bold text-yellow-600 bg-yellow-100 px-2 py-0.5 rounded-full text-xs">{atRisk.length}</span>
                </li>
                <li className="flex justify-between items-center">
                  <span className="text-sm font-medium text-ink/70">Suggestions</span>
                  <span className="font-bold text-blue-600 bg-blue-100 px-2 py-0.5 rounded-full text-xs">{suggestions.length}</span>
                </li>
                <li className="flex justify-between items-center">
                  <span className="text-sm font-medium text-ink/70">Positive Notes</span>
                  <span className="font-bold text-green-600 bg-green-100 px-2 py-0.5 rounded-full text-xs">{positive.length}</span>
                </li>
              </ul>
              
              <div className="mt-8 pt-6 border-t border-ledger-line text-xs text-ink/50 text-center leading-relaxed">
                Insights are automatically generated nightly based on your assignment submissions, attendance records, and peer benchmarks.
              </div>
            </div>
          </div>

        </div>
      )}
    </div>
  )
}
